config/routes.rb
Photogur::Application.routes.draw do
  resources :pictures

  

  

  post 'pictures' => "pictures#create"

  get 'pictures' => 'pictures#index'
  get 'pictures/new' => 'pictures#new'
  get 'pictures/:id/edit' => "pictures#edit", as: "edit_picture"
  get 'pictures/:id' => 'pictures#show', as: "picture"

  root :to => "pictures#index"
  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :artist, :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
	  @pictures = Picture.all
	end

	
	# def picture0
	# 	@picture = {
	# 		:title => "The old church on the coast of White sea",
	#   	:artist => "Sergey Ershov",
	#   	:url => "http://monicao.s3.amazonaws.com/bitmaker/house.jpg"
	# 	}
	# end

	# def picture1
	# 	@picture = {
	#   		:title => "Sea Power",
	#   		:artist => "Stephen Scullion",
	#   		:url => "http://monicao.s3.amazonaws.com/bitmaker/wave.jpg"
	#   }
	# end

	# def picture2
	# 	@picture = {
	# 		:title => "Into the Poppies",
	#   	:artist => "John Wilhelm",
	#   	:url => "http://monicao.s3.amazonaws.com/bitmaker/girl.jpg"
	# 	}
	# end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])

		if @picture.update_atributes(params[:id])
			redirect_to "/pictures/#{@picture.id}"
		else
			render :edit
		end
	end

	def show
  	@picture = Picture.find(params[:id])
	end

	def new
		@picture = Picture.new
	end

	def create
	  # Make the variable @picture a new picture with the given params
	  @picture = Picture.new(params[:picture])
	  if @picture.save
	    # if the save for the picture was successful, go to index.html.erb
	    redirect_to pictures_url
	  else
	    # otherwise render the view associated with the action :new (i.e. new.html.erb)
	    render :new
	  end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<head>
	  <title>Photogur</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
	</head>

<body> 
		<nav>
			<ul>
			  	<li><a href="http://localhost:3000/pictures/new">Upload Picture<br /></a></li>
			  	<li><a href="#">Home<br /></a></li>
			  	<li><a href="#">About us<br /></a></li>
			  	<li><a href="#">Edit a Photo<br /></a></li>
			  	<li><a href="#">Destroy a photo<br /></a></li>
			  	<li><a href="#">Sign in<br /></a></li>
			  	<li><a href="#">Register<br /></a></li>
			  	
			</ul>
		</nav>
	<div class="container">
		<div class="header">
			

			
		<article id='slider'>
    <input type='radio' name='slider' id='slide1' checked />
    <input type='radio' name='slider' id='slide2' />
    <input type='radio' name='slider' id='slide3' />
    <input type='radio' name='slider' id='slide4' />
    <input type='radio' name='slider' id='slide5' />
    <div id='slides'>
        <div id='overflow'>
            <div class='inner'>
            	<% @pictures.each do |picture| %>
                <article>
                    <img src="<%=picture[:url]%>" />
                </article>
                <% end %>
            </div>
        </div>
    </div>
    <div id='controls'>
        <label for='slide1'></label>
        <label for='slide2'></label>
        <label for='slide3'></label>
        <label for='slide4'></label>
        <label for='slide5'></label>
    </div>
    <div id='active'>
        <label for='slide1'></label>
        <label for='slide2'></label>
        <label for='slide3'></label>
        <label for='slide4'></label>
        <label for='slide5'></label>
    </div>
</article>
</div>
				
				
				

			
		
	<div class="content">


		<div class="section second"></div>
			
			
	</div>
	<div class="footer">
<!-- 				<div id="nametag">
					<div class="pic">
						<hgroup>
							<h1>Ian Steffy</h1>
							<h2>web dev</h2>
						</hgroup>
					</div> 

					<div id="introduction">
						<p>I'm a student at Bitmaker Labs who lives and breaths code</p>
					</div>

					<div id="contact">
						<a href="mailto:isteffy@hotmail.com" id="email" class="button">Email <span>isteffy@hotmail.com</span></a>
					</div> -->
				</div>
			</div>
</div>
</body>

</html>

app/views/pictures/delete.html.erb
<h1>Delete Picture</h1>
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %>
<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= submit_tag "Save" %>
  </p>
<% end %>

app/views/pictures/index.html.erb
<!-- <div class="section third"></div>
<div class="content"><div></div></div> -->

<!-- 	<div class="blurred">
		<iframe height="3000" frameborder="0" scrolling="no" ></iframe>
		<p>Photogur</p>
</div> -->

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pictures_url %>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= f.submit "Save" %> 
  </p>
<% end %>

app/views/pictures/picture.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src="<%= @picture[:url] %>">
<% end %>

app/views/pictures/picture0.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src="<%= @picture[:url] %>">

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %>

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<%= image_tag @picture.url %>

<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %>